use_frameworks!

platform :ios, '9.0'

target 'OIDateManager_Example' do
  pod 'OIDateManager', :path => '../'

  target 'OIDateManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
